/*global define */
define({
	BTN_ADD:				'Add',
	BTN_PREFERENCES:		'Preferences',
	BTN_SYNC_TASKS:			'Sync Tasks',
	BTN_BOARDS:				'Boards',
	BTN_LISTS:				'Lists',
	BTN_CARDS:				'Cards',
	BTN_TASKS:				'Tasks',
	BTN_SAVE:				'Save',
	BTN_CANCEL:				'Cancel',
	BTN_DONE:				'Done',
	ADD_NEW_BOARD:			'Add New Board',
	ADD_NEW_LIST:			'Add New List',
	ADD_NEW_CARD:			'Add New Card',
	ADD_NEW_TASKS:			'Add New Tasks',
	ERR_CONNECTION:			'Cannot connect to internet',
	LBL_CREATE_NEW_BOARD:	'Create New Board',
	LBL_BOARD_NAME:			'Board Name',
	LBL_CREATE_NEW_LIST:	'Create New List',
	LBL_LIST_NAME:			'List Name',
	LBL_PREFERENCES_TITLE:	'Brackets Trello Preferences',
	LBL_TRELLO_API_TOKEN:	'Trello API Token',
	LBL_AUTOSYNC_TIME:		'AutoSync Time (Seconds)',
	LBL_SAVE_PROJECT_PREFS:	'Save Prefs in Project',
	LBL_CREATE_NEW_CARD:	'Create New Card',
	LBL_CARD_NAME:			'Card Name',
	LBL_CARD_DESC:			'Card Description',
	LBL_CREATE_NEW_TASKS:	'Create New Tasks',
	LBL_TASK_NAME:			'Add Task Name',
	LBL_ADD_NEW_TASK:		'Add New',
	MSG_NEW_BOARD:			'New board has been created.',
	MSG_NEW_LIST:			'New list has been created.',
	MSG_NEW_CARD:			'New card has been created.',
	MSG_NEW_TASKS:			'New tasks have been added to the card.',
	MSG_AUTOSYNC_TIME:		'AutoSync time must be more than 2 seconds.'
});