/*global define */
define({
	BTN_ADD:				'Add',
	BTN_PREFERENCES:		'Preferences',
	BTN_SYNC_TASKS:			'Sync Tasks',
	BTN_BOARDS:				'Boards',
	BTN_LISTS:				'Lists',
	BTN_CARDS:				'Cards',
	BTN_TASKS:				'Tasks',
	BTN_SAVE:				'Save',
	BTN_CANCEL:				'Cancel',
	BTN_DONE:				'Done',
	BTN_YES:				'Yes',
	BTN_ADD_NEW_MEMEBERS: 	'Add New Memebers',
	BTN_ADD_COMMENT: 		'Add Comment',
	BTN_ADD_NEW_CHECKLIST: 	'Add New Checklist',
	BTN_ADD_NEW_TASK:		'Add New Task',
	BTN_ADD_NEW_TASKS:		'Add New Tasks',
	BTN_ADD_NEW_BOARD:			'Add New Board',
	BTN_ADD_NEW_LIST:			'Add New List',
	BTN_ADD_NEW_CARD:			'Add New Card',
	
	ERR_CONNECTION:			'Cannot connect to internet',
	LBL_BOARD_NAME:			'Board Name',
	LBL_LIST_NAME:			'List Name',
	LBL_PREFERENCES_TITLE:	'Brackets Trello Preferences',
	LBL_TRELLO_API_TOKEN:	'Trello API Token',
	LBL_AUTOSYNC_TIME:		'AutoSync Time (Seconds)',
	LBL_SAVE_PROJECT_PREFS:	'Save Prefs in Project',
	LBL_CARD_NAME:			'Card Name',
	LBL_CARD_DESC:			'Card Description',
	LBL_TASK_NAME:			'Task Name',
	LBL_COMMENTS: 			'Comments',
	LBL_MEMBERS: 			'Memebers',
	LBL_CARD_DESC:			'Card Description',
	LBL_CHECKLIST_NAME:		'Checklist Name',
	LBL_COMMENT:			'Comment',
	
	MSG_NEW_BOARD:			'New board has been created.',
	MSG_NEW_LIST:			'New list has been created.',
	MSG_NEW_CARD:			'New card has been created.',
	MSG_NEW_TASKS:			'New tasks have been added to the card.',
	MSG_AUTOSYNC_TIME:		'AutoSync time must be more than 2 seconds.',
	MSG_DELETE_BOARD:		'Are you sure you want to archive this board?',
	MSG_DELETE_LIST:		'Are you sure you want to archive this list?',
	MSG_DELETE_CARD:		'Are you sure you want to archive this card?',
	MSG_DELETE_TASK:		'Are you sure you want to delete this task?',
	MSG_DELETE_CHECKLIST:	'Are you sure you want to delete this checklist?',
	MSG_DELETE_COMMENT:		'Are you sure you want to delete this comment?',
	MSG_DELETE_MEMBER:		'Are you sure you want to remove this member?',
	
	TIP_GET_YOUR_TOKEN:		'Get Your Token ',
	TIP_HERE:				'here',
	CHK_AUTO_SYNC:			'AutoSync',
	LIST_CHANGES:			'Changes',
	
	TITLE_CREATE_NEW_BOARD: 'Create New Board',
	TITLE_CONFIRM:			'Confirmation',
	TITLE_EDIT_BOARD_NAME: 	'Edit Board Name',
	TITLE_EIDT_CARD_DESC:	'Edit Card Description',
	TITLE_CREATE_NEW_TASKS: 'Create New Tasks',
	TITLE_EDIT_CARD_NAME:	'Edit Card Name',
	TITLE_EDIT_CHECKLIST_NAME:	'Edit Checklist Name',
	TITLE_CREATE_NEW_CHECKLIST: 'Create New Checklist',
	TITLE_EDIT_COMMENT:			'Edit Comment',
	TITLE_EDIT_LIST_NAME: 		'Edit List Name',
	TITLE_EDIT_TASK_NAME: 		'Edit Task Name',
	TITLE_ADD_NEW_COMMENT: 		'Add New Comment',
	TITLE_CREATE_NEW_LIST: 		'Create New List',
	TITLE_ADD_NEW_MEMBERS: 		'Add New Memebers',
	TITLE_CREATE_NEW_CARD: 		'Add New Card',
	
	/////////////////////////////////////////////////////////////////////////
	///////////////////// TOOLTIPS 	/////////////////////////////////////////
	/////////////////////////////////////////////////////////////////////////
	EDIT_BOARD_NAME:		'Edit board name',
	DELETE_BOARD:			'Delete board',
	EDIT_LIST_NAME:			'Edit list name',
	DELETE_LIST:			'Delete list',
	PUSH_COMMENT:			'Push comment to Trello',
	PUSH_ALL_COMMENTS:		'Push all list comments to Trello',
	EDIT_CARD_NAME:			'Edit card name',
	DELETE_CARD:			'Delete card',
	EDIT_CARD_DESC:			'Edit card description',
	EDIT_CHECKLIST_NAME:	'Edit checklist name',
	DELTE_CKECKLIST:		'Delete checklist',
	HIDE_CHECKED:			'Hide checked items',
	ADD_COMMENT:			'Add card comment',
	EDIT_COMMENT:			'Edit card comment',
	DELETE_COMMENT:			'Delete card comment',
	DELETE_MEMBER:			'Delete member'
});
