/*global define */
define({
	BTN_ADD:				'新增',
	BTN_PREFERENCES:		'配置',
	BTN_SYNC_TASKS:			'同步',
	BTN_BOARDS:				'板块',
	BTN_LISTS:				'列表',
	BTN_CARDS:				'卡片',
	BTN_TASKS:				'任务',
	BTN_SAVE:				'保存',
	BTN_CANCEL:				'取消',
	BTN_DONE:				'完成',
	BTN_YES:				'是',
	BTN_ADD_NEW_MEMEBERS: 	'新增成员',
	BTN_ADD_COMMENT: 		'添加注释',
	BTN_ADD_NEW_CHECKLIST: 	'新增检查单',
	BTN_ADD_NEW_TASK:		'新增检查项',
	BTN_ADD_NEW_TASKS:		'新增检查项',	
	BTN_ADD_NEW_BOARD:		'新增板块',
	BTN_ADD_NEW_LIST:		'新增列表',
	BTN_ADD_NEW_CARD:		'新增卡片',

	LBL_BOARD_NAME:			'板块名',
	LBL_LIST_NAME:			'列表名',
	LBL_PREFERENCES_TITLE:	'配置',
	LBL_TRELLO_API_TOKEN:	'Trello的API令牌',
	LBL_AUTOSYNC_TIME:		'自动同步间隔(秒)',
	LBL_SAVE_PROJECT_PREFS:	'在项目中保存配置项',
	LBL_CARD_NAME:			'卡片名',
	LBL_CARD_DESC:			'卡片描述',
	LBL_TASK_NAME:			'检查项名',
	LBL_COMMENTS: 			'注释',
	LBL_MEMBERS: 			'成员',
	LBL_CARD_DESC:			'卡片描述',
	LBL_CHECKLIST_NAME:		'检查单名',
	LBL_COMMENT:			'注释',
	
	MSG_NEW_BOARD:			'新板块已创建完成。',
	MSG_NEW_LIST:			'新列表已创建完成。',
	MSG_NEW_CARD:			'新卡片已创建完成。',
	MSG_NEW_TASKS:			'新检查项已添加到卡片上。',
	MSG_AUTOSYNC_TIME:		'自动同步间隔必须大于2秒。',
	MSG_DELETE_BOARD:		'是否确定完成该版块？',
	MSG_DELETE_LIST:		'是否确定完成该列表？',
	MSG_DELETE_CARD:		'是否确定完成该卡片？',
	MSG_DELETE_TASK:		'是否确定删除该检查项？',
	MSG_DELETE_CHECKLIST:	'是否确定删除该检查单？',
	MSG_DELETE_COMMENT:		'是否确定删除该注释？',
	MSG_DELETE_MEMBER:		'是否确定移除该成员？',
	
	ERR_CONNECTION:			'不能连接到网络',
	TIP_GET_YOUR_TOKEN:		'获取你的令牌 ',
	TIP_HERE:				'这里',
	CHK_AUTO_SYNC:			'自动同步',
	LIST_CHANGES:			'变化',
	
	TITLE_CREATE_NEW_TASKS: '新增检查项',
	TITLE_CREATE_NEW_BOARD: '新增板块',
	TITLE_CONFIRM:			'确认',
	TITLE_EDIT_BOARD_NAME: 	'修改板块名',
	TITLE_EIDT_CARD_DESC:	'修改卡片描述',
	TITLE_EDIT_CARD_NAME:	'修改卡片名',
	TITLE_EDIT_CHECKLIST_NAME:	'修改检查单名',
	TITLE_CREATE_NEW_CHECKLIST: '新增检查单',
	TITLE_EDIT_COMMENT:			'修改注释',
	TITLE_EDIT_LIST_NAME: 		'修改列表名',
	TITLE_EDIT_TASK_NAME: 		'修改检查项名',
	TITLE_ADD_NEW_COMMENT: 		'新增注释',
	TITLE_CREATE_NEW_LIST: 		'新增列表',
	TITLE_ADD_NEW_MEMBERS: 		'新增成员',
	TITLE_CREATE_NEW_CARD:		'新增卡片',
	
	/////////////////////////////////////////////////////////////////////////
	///////////////////// TOOLTIPS 	/////////////////////////////////////////
	/////////////////////////////////////////////////////////////////////////
	EDIT_BOARD_NAME:		'修改板块名',
	DELETE_BOARD:			'删除板块',
	EDIT_LIST_NAME:			'修改列表名',
	DELETE_LIST:			'删除列表',
	PUSH_COMMENT:			'上传注释到Trello',
	PUSH_ALL_COMMENTS:		'上传所有注释到Trello',
	EDIT_CARD_NAME:			'修改卡片名',
	DELETE_CARD:			'删除卡片',
	EDIT_CARD_DESC:			'修改卡片描述',
	EDIT_CHECKLIST_NAME:	'修改检查单名字',
	DELTE_CKECKLIST:		'删除检查单',
	HIDE_CHECKED:			'隐藏完成项',
	ADD_COMMENT:			'添加卡片注释',
	EDIT_COMMENT:			'修改卡片注释',
	DELETE_COMMENT:			'删除卡片注释',
	DELETE_MEMBER:			'移除成员'
});
