/*global define */
define({
	BTN_ADD:				'Hinzufügen',
	BTN_PREFERENCES:		'Einstellungen',
	BTN_SYNC_TASKS:			'Synchronisieren',
	BTN_BOARDS:				'Boards',
	BTN_LISTS:				'Lists',
	BTN_CARDS:				'Cards',
	BTN_TASKS:				'Tasks',
	BTN_SAVE:				'Speichern',
	BTN_CANCEL:				'Abbrechen',
	BTN_DONE:				'Fertig',
	BTN_YES:				'Ja',
	BTN_ADD_NEW_MEMEBERS: 	'Neues Mitglied hinzufügen',
	BTN_ADD_COMMENT: 		'Neuen Kommentar hinzufügen',
	BTN_ADD_NEW_CHECKLIST: 	'Neue Checklist hinzufügen',
	BTN_ADD_NEW_TASK:		'Neue Aufgabe hinzufügen',
	BTN_ADD_NEW_TASKS:		'Neue Aufgaben hinzufügen',
	BTN_ADD_NEW_BOARD:		'Neues Board hinzufügen',
	BTN_ADD_NEW_LIST:		'Neue Liste hinzufügen',
	BTN_ADD_NEW_CARD:		'Neue Karte hinzufügen',
	
	ERR_CONNECTION:			'Verbindung zum Internet fehlgeschlagen',
	LBL_BOARD_NAME:			'Name des Boards',
	LBL_LIST_NAME:			'Name der Liste',
	LBL_PREFERENCES_TITLE:	'Brackets Trello Einstellungen',
	LBL_TRELLO_API_TOKEN:	'Trello API Token',
	LBL_AUTOSYNC_TIME:		'Autosynchronisiationsdauer (Sekunden)',
	LBL_SAVE_PROJECT_PREFS:	'Speichere die Einstellungen im Projekt',
	LBL_CARD_NAME:			'Kartenname',
	LBL_CARD_DESC:			'Beschreibung der Karte',
	LBL_TASK_NAME:			'Aufgabenname',
	LBL_COMMENTS: 			'Kommentar',
	LBL_MEMBERS: 			'Mitglieder',
	LBL_CHECKLIST_NAME:		'Checklist Name',
	LBL_COMMENT:			'Kommentar',
	
	MSG_NEW_BOARD:			'Es wurde ein neues Board erstellt.',
	MSG_NEW_LIST:			'Es wurde eine neue Liste erstellt.',
	MSG_NEW_CARD:			'Es wurde eine neue Karte erstellt.',
	MSG_NEW_TASKS:			'Es wurden neue Aufgaben zur Karte hinzugefügt.',
	MSG_AUTOSYNC_TIME:		'Die Autosynchronisationsdauer muss größer als 2 Sekunden sein.',
	MSG_DELETE_BOARD:		'Sind Sie sicher, dass Sie dieses Board archivieren wollen?',
	MSG_DELETE_LIST:		'Sind Sie sicher, dass Sie diese Liste archivieren wollen?',
	MSG_DELETE_CARD:		'Sind Sie sicher, dass Sie diese Karte archivieren wollen?',
	MSG_DELETE_TASK:		'Sind Sie sicher, dass Sie diese Aufgabe archivieren wollen?',
	MSG_DELETE_CHECKLIST:	'Sind Sie sicher, dass Sie diese Checklist archivieren wollen?',
	MSG_DELETE_COMMENT:		'Sind Sie sicher, dass Sie diesen Kommentar archivieren wollen?',
	MSG_DELETE_MEMBER:		'Sind Sie sicher, dass Sie dieses Mitglied entfernen wollen?',
	
	TIP_GET_YOUR_TOKEN:		'Token anzeigen',
	TIP_HERE:				'hier',
	CHK_AUTO_SYNC:			'Automatische Synchronisation',
	LIST_CHANGES:			'Veränderungen',
	
	TITLE_CREATE_NEW_BOARD: 	'Neues Board erstellen',
	TITLE_CONFIRM:				'Bestätigen',
	TITLE_EDIT_BOARD_NAME: 		'Name des Boards bearbeiten',
	TITLE_EIDT_CARD_DESC:		'Die Beschreibung der Karte bearbeiten',
	TITLE_CREATE_NEW_TASKS: 	'Neue Aufgabe erstellen',
	TITLE_EDIT_CARD_NAME:		'Name der Karte bearbeiten',
	TITLE_EDIT_CHECKLIST_NAME:	'Name der Checklist bearbeiten',
	TITLE_CREATE_NEW_CHECKLIST: 'Neue Checklist erstellen',
	TITLE_EDIT_COMMENT:			'Kommentar bearbeiten',
	TITLE_EDIT_LIST_NAME: 		'Name der Liste bearbeiten',
	TITLE_EDIT_TASK_NAME: 		'Name der Aufgabe bearbeiten',
	TITLE_ADD_NEW_COMMENT: 		'Neuen Kommentar erstellen',
	TITLE_CREATE_NEW_LIST: 		'Neue Liste erstellen',
	TITLE_ADD_NEW_MEMBERS: 		'Neues Mitglied hinzufügen',
	TITLE_CREATE_NEW_CARD: 		'Neue Karte erstellen',
	
	/////////////////////////////////////////////////////////////////////////
	///////////////////// TOOLTIPS 	/////////////////////////////////////////
	/////////////////////////////////////////////////////////////////////////
	EDIT_BOARD_NAME:		'Name des Boards bearbeiten',
	DELETE_BOARD:			'Board löschen',
	EDIT_LIST_NAME:			'Name der Liste bearbeiten',
	DELETE_LIST:			'Liste löschen',
	PUSH_COMMENT:			'Kommentar zu Trello hochladen',
	PUSH_ALL_COMMENTS:		'Alle Kommentare dieser Liste zu Trello hochladen',
	EDIT_CARD_NAME:			'Name der Karte bearbeiten',
	DELETE_CARD:			'Karte löschen',
	EDIT_CARD_DESC:			'Beschreibung der Karte bearbeiten',
	EDIT_CHECKLIST_NAME:	'Name der Checklist bearbeiten',
	DELTE_CKECKLIST:		'Checklist löschen',
	HIDE_CHECKED:			'Alle fertiggestellten Einträge ausblenden',
	ADD_COMMENT:			'Neuen Kommentar zur Karte hinzufügen',
	EDIT_COMMENT:			'Kommentar bearbeiten',
	DELETE_COMMENT:			'Kommentar löschen',
	DELETE_MEMBER:			'Mitglied entfernen'
});